---
- name: Install backupninja packages
  apt: name="{{item}}" state=present
  with_items:
    - dialog
    - backupninja
  when:
    - ansible_os_family == "Debian"
    - enable_backups|bool

- name: Install backupninja packages
  yum: name="{{item}}" state=present
  with_items:
    - dialog
    - backupninja
  when:
    - ansible_os_family == "RedHat"
    - enable_backups|bool

- name: Create reports directory
  file: state=directory path="{{item}}" owner=root group={{backupninja_admingroup}} mode=0700
  with_items:
    - "{{backupninja_configdir}}"
    - "{{backupninja_reportdir}}"
  tags:
    - backupninja
  when:
    - enable_backups|bool

- name: Copy additional backupninja plugins
  copy: src="{{item}}" dest="/usr/share/backupninja/{{item}}" owner=root group=root mode=0644
  with_items:
    - mongodb
    - mongodb.helper
  when:
    - backupninja_support_mongodb|bool
    - enable_backups|bool

- name: Copy template files
  template:
    src: "{{item}}.j2"
    dest: "/etc/backup.d/{{item}}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - "{{ backupninja_backup_templates }}"
  when:
    - enable_backups|bool

- name: Copy RSA key
  template:
    src: backup_rsa
    dest: /root/.ssh/backup_rsa
    owner: root
    group: root
    mode: 0600
  when:
    - enable_backups|bool

- name: Configure backup-host in ssh config for root
  blockinfile:
    path: "/root/.ssh/config"
    owner: "root"
    group: "root"
    mode: "0600"
    create: "yes"
    block: |
      host {{backupninja_rdiff_host}}
        HostName {{backup_domain}}
        User {{backup_name}}
        AddressFamily inet
        IdentityFile /root/.ssh/backup_rsa
  when:
    - enable_backups|bool

- name: Template backupninja.conf
  template: src="backupninja.conf.j2" dest="/etc/backupninja.conf" owner=root group=root mode=0600
